export default function Playlist(){
    return(
        <>
        <h1 className=" text-2xl font-extrabold  text-black text-center">Welcome To Playlisttt </h1>
        <section className="grid grid-cols-3 mt-7 mx-6 gap-">
            
            <div className="">
                <iframe width="400" height="250" className="rounded-xl "src="https://www.youtube.com/embed/6LD30ChPsSs?si=9nj47dLy2oqB9hKD" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></div>
                <div> <iframe width="400" height="250" className="rounded-xl "src="https://www.youtube.com/embed/k9_JbEaRxso?si=3_IvVxgJ-aNzVezq" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></div>
                <div><iframe width="400" height="250" className="rounded-xl "src="https://www.youtube.com/embed/KgpnfT5bgLY?si=izZmVKKtR2hPMQmu" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></div>
                <div><iframe width="400" height="250" className="rounded-xl "src="https://www.youtube.com/embed/3Lc-96oH__s?si=lY1Mbp5CuWR7IZlU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></div>
                <div><iframe width="400" height="250" className="rounded-xl "src="https://www.youtube.com/embed/v0pXMxU87JQ?si=_UHkaImXzoBFzjZ3" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></div>
                <div><iframe width="400" height="250" className="rounded-xl "src="https://www.youtube.com/embed/xpWqfS8Su_Y?si=qf8dBVAZFvwMJfNm" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></div>
                <div><iframe width="400" height="250" className="rounded-xl "src="https://www.youtube.com/embed/KgpnfT5bgLY?si=izZmVKKtR2hPMQmu" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></div>
                <div><iframe width="400" height="250" className="rounded-xl "src="https://www.youtube.com/embed/3Lc-96oH__s?si=lY1Mbp5CuWR7IZlU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></div>
                <div><iframe width="400" height="250" className="rounded-xl "src="https://www.youtube.com/embed/v0pXMxU87JQ?si=_UHkaImXzoBFzjZ3" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></div>
                <div><iframe width="400" height="250" className="rounded-xl "src="https://www.youtube.com/embed/xpWqfS8Su_Y?si=qf8dBVAZFvwMJfNm" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></div>
                <div><iframe width="400" height="250" className="rounded-xl "src="https://www.youtube.com/embed/KgpnfT5bgLY?si=izZmVKKtR2hPMQmu" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></div>
                <div><iframe width="400" height="250" className="rounded-xl "src="https://www.youtube.com/embed/3Lc-96oH__s?si=lY1Mbp5CuWR7IZlU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></div>
                <div><iframe width="400" height="250" className="rounded-xl "src="https://www.youtube.com/embed/v0pXMxU87JQ?si=_UHkaImXzoBFzjZ3" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></div>
                <div><iframe width="400" height="250" className="rounded-xl "src="https://www.youtube.com/embed/xpWqfS8Su_Y?si=qf8dBVAZFvwMJfNm" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></div>
           

        </section>
        </>
    )
}